In [1]:
import pandas as pd

In [2]:
polls = pd.read_csv('Resources/poll_numbers.csv')
polls = polls.rename(columns = {'name' : 'candidate'})

polls

    candidate      date    percent
0       Biden  2/7/2020  24.262710
1       Biden  2/6/2020  24.275590
2   Buttigieg  2/7/2020   8.373781
3   Buttigieg  2/6/2020   8.359316
4   Klobuchar  2/6/2020   3.779541
5   Klobuchar  2/7/2020   3.777914
6     Sanders  2/7/2020  21.375820
7     Sanders  2/6/2020  21.377460
8      Steyer  2/6/2020   2.219085
9      Steyer  2/7/2020   2.220774
10     Warren  2/7/2020  13.283940
11     Warren  2/6/2020  13.272080
12       Yang  2/6/2020   4.168553
13       Yang  2/7/2020   4.174042

In [3]:
polls = polls.pivot(index = 'candidate', columns='date', values='percent')
polls

date        2/6/2020   2/7/2020
candidate
Biden      24.275590  24.262710
Buttigieg   8.359316   8.373781
Klobuchar   3.779541   3.777914
Sanders    21.377460  21.375820
Steyer      2.219085   2.220774
Warren     13.272080  13.283940
Yang        4.168553   4.174042

In [4]:
polls['candidate_id'] = [1,2,3,4,5,6,7]
polls

date        2/6/2020   2/7/2020  candidate_id
candidate
Biden      24.275590  24.262710             1
Buttigieg   8.359316   8.373781             2
Klobuchar   3.779541   3.777914             3
Sanders    21.377460  21.375820             4
Steyer      2.219085   2.220774             5
Warren     13.272080  13.283940             6
Yang        4.168553   4.174042             7

In [5]:
polls = polls.reset_index()
polls = polls.set_index(['candidate_id', 'candidate'])
polls

date                     2/6/2020   2/7/2020
candidate_id candidate
1            Biden      24.275590  24.262710
2            Buttigieg   8.359316   8.373781
3            Klobuchar   3.779541   3.777914
4            Sanders    21.377460  21.375820
5            Steyer      2.219085   2.220774
6            Warren     13.272080  13.283940
7            Yang        4.168553   4.174042

In [6]:
polls.to_csv('Final/poll_count.csv')